# Generated by Django 4.2.25 on 2025-10-14 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bullets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bullets', models.TextField()),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='app1.artigos')),
            ],
        ),
        migrations.DeleteModel(
            name='Sugestao',
        ),
    ]
