# Generated by Django 4.2.24 on 2025-10-16 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_bullets_delete_sugestao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigos',
            name='sugestao',
        ),
    ]
