# Generated by Django 4.2.24 on 2025-10-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_artigos_sugestao'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progresso_diario',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='progresso_diario',
            name='visitante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='progresso_diario',
            name='user',
        ),
    ]
