# Generated by Django 4.2.24 on 2025-10-24 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_progresso_diario_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progresso_diario',
            unique_together={('visitante', 'data')},
        ),
    ]
