# Generated by Django 4.2.24 on 2025-11-14 12:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0005_alter_progresso_diario_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigos',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='artigos_favoritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
