# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - jcprojeto

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # ✅ Corrigido: install requirements.txt da raiz
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 🧹 Limpa arquivos locais que não devem ir pro deploy
      - name: Cleaning testing files
        run: |
          rm -f db.sqlite3
          rm -f .env

      # 📦 Compacta os arquivos do projeto para upload
      - name: Zip artifact for deployment
        run: |
          zip release.zip ./* -r

      # ⬆️ Envia o artefato para o job de deploy
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FB27835AFA844A349BC4F7C55F2B1E1F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_114A337D71554EA380E122C848FFB05F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B224687249BE41CEBC7D37376D044432 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@
